### ISSUE TITLE
add format_checker_for

### ISSUE THREAD

**Issue by kenjones-cisco** [Julian/jsonschema#197]
Similar to how validators have:

```
def validator_for(schema, default=_unset):
    if default is _unset:
        default = Draft4Validator
    return meta_schemas.get(schema.get(u"$schema", u""), default)
```

Within _format.py, add something like the following:

```
checkers = {'<draft_version_key>3': draft3_format_checker,
                   '<draft_version_key>4': draft4_format_checker,
                  }
def format_checker_for(schema, default=_unset):
    if default is _unset:
        default = draft4_format_checker
    return checkers.get(schema.get(u"$schema", u""), default)
```

**Comment by Julian** [comment]
The reason this doesn't exist is basically:

* There's no association between validators and formatters -- you can create a new validator, and there's no API for saying which formatter it's associated with, and there may or may not be one
* Doing this anyhow is just a simple dict lookup or conditional. The only reason `validator_for` exists is that it's handling `$schema` so that users don't have to.
