### ISSUE TITLE
cannot find a file if $ref is a relative path

### ISSUE THREAD

**Issue by weerp** [Julian/jsonschema#220]
The issue is the same as issue:
"Reference to local files (with relative/no path) doesn't work #98"

**Comment by Julian** [comment]
Hi!

Thanks for the report.

The issue you linked is a bit long, but did you consult the comments there?

It's true, `$ref` will not be able to find files if you put relative paths in it, because `$ref` is defined to take URLs, and you cannot put relative paths there unless you somehow define a base URL. You can do that via the `id` ref or by appropriately configuring your ref resolver.

Please take a look at that ticket and feel free to bring up any issues you have on the mailing list if you can't get it to work.

**Comment by weerp** [comment]
Hello Julian,

The @sblask's solution is not common. It does not applicable for case of json schema files located in different folders with chain reference as bellow.
root_dir/dir_1/A.json
root_dir/dir_2/B.json
root_dir/dir_3/C.json

in A.json
{
    ....
    {"$ref": "dir_2/B.json#/definitions/positiveInteger1"}
}
in B.json
{
    ....
    {"$ref": "dir_3/C.json#/definitions/positiveInteger"}
}
