### ISSUE TITLE
[QUESTION] How to validate undefined keys

### ISSUE THREAD

**Issue by csarcom** [Julian/jsonschema#221]
```python
{
u'error_settings': {
                '0s': [u'400',u'403'],
                '30s': [u'404', u'405', u'414',]
            },
}
```

Problem: keys '0s' and '30s' are not always like that, could be eg.:
```python
{
u'error_settings': {
                '10s': [u'400',u'403'],
                '50s': [u'404', u'405', u'414',]
            },
}
```

Is there a way to validate it?

**Comment by Julian** [comment]
Hi! Please use the mailing list, either for this implementation, or for json schema itself, for questions, so that the bug tracker can be used for tracking issues. Both forums live on google groups:

Core Development: https://groups.google.com/forum/#!forum/json-schema
This Implementation: https://groups.google.com/forum/#!forum/jsonschema

To answer your question, you might want `patternProperties`.
