### ISSUE TITLE
__unicode__() returns much more information than e.message on ValidationError()

### ISSUE THREAD

**Issue by grahamhayes** [Julian/jsonschema#240]
__unicode__() returns a lot more info than the message.

In python3 we are supposed to use the __unicode__() method to get the message, and this means that the output in python2 != python3.

**Comment by Julian** [comment]
Hey.

It's true, it does -- but there's no specific guarantee (or de facto standard other than what I'll mention) on what it means to call `unicode` / `str` on arbitrary classes.

If you want the message, you'd access `e.message`. `ValidationError` defines `__unicode__` that way because that's how `Exception` defines output for exception tracebacks.

Which output differs for you between Python2 and Python3?

Feel free to follow up with any questions / concerns.

**Comment by grahamhayes** [comment]
In Python 3 e.message has been deprecated - apparently the advice for the replacement is to us the \_\_unicode\_\_() method. Having different content makes this interesting for us.....

**Comment by Julian** [comment]
e.message is deprecated on Exceptions that don't specifically define an
attribute called message, I.e. it's deprecated to assume that the first
positional arg to an exception subclass is automatically the message.
That's not the case here, message is an explicit attribute of
ValidationErrors.

In Python 3 e.message has been deprecated - apparently the advice for the
replacement is to us the __unicode__() method. Having different content
makes this interesting for us.....

—
Reply to this email directly or view it on GitHub
<https://github.com/Julian/jsonschema/issues/240#issuecomment-122956573>.
