### ISSUE TITLE
Validator doesn't like UTF-8 with BOM

### ISSUE THREAD

**Issue by kprovost** [Julian/jsonschema#267]
The validator can fail for files which start with a UTF-8 BOM.
When resolving references we eventually end up in 'def resolve_remote', which does:

    else:
            # Otherwise, pass off to urllib and assume utf-8
            result = json.loads(urlopen(uri).read().decode("utf-8"))

This fails if the uri points to a UTF-8 file with a BOM. It works fine if decode uses "utf-8-sig" instead.

**Comment by Julian** [comment]
That branch is really just a fallback to *try* something rather than blowing up. There really can't be a 100% correct answer there obviously.

Does your resolution work if you use requests?

**Comment by kprovost** [comment]
It's not immediately clear to me how I could do that. I've been using a very simple "$ref": "filename.json#/definitions/foo" reference. There's no schema indication (and I use the resolver so I can have relative paths).

**Comment by Julian** [comment]
Install `requests`, change the ref to be a `file://` schemed URL.

I think I'm gonna close this out because regardless of what codec is used here, it's always going to be wrong for something, as I mentioned, it's just a fallback, but if you need more guidance, please send a post to the mailing list.

Thanks, (and sorry for the delay).
