### ISSUE TITLE
On handling relative file:// $refs

### ISSUE THREAD

**Issue by purukaushik** [Julian/jsonschema#289]
Hey @Julian,
I added the resolution of local relative file uris in RefResolver ( validator.py) for a project requirement.
```
elif scheme in [u"file"]:
            uri_path = urlsplit(uri).path
            print "uri" + uri_path
            from os.path import isfile
            if isfile(uri_path):
                result = json.loads(open(""+uri_path).read())
            else:
                print "resolving as relative path"
                result = json.loads(open("./"+uri_path).read())
```
[link to code](https://github.com/purukaushik/jsonschema/blob/master/jsonschema/validators.py#L419)

I was wondering why this wasn't handled originally. I can drop a PR if you wish to have this included in your next release.

**Comment by Julian** [comment]
Hi!

Relative file references are by definition not portable, which is the basic reason why -- that being said though the typical thing people do when they still want to use them is to use a RefResolver with a base_uri that's the cwd (there should be some examples of this in other issues).

-- which isn't to say I don't hear feedback about this often enough to want to make this easier to do :) -- but I think rather than special casing things the way you have it (which has a race condition and some cross-platform issues :P), I'd prefer that these sorts of things be done as schema transformations -- i.e., that jsonschema could potentially provide a `resolve_relative_refs()` function that took a schema-ish (thing with relative file refs) and produced a new schema where all relative refs were resolved relative to a directory.

**Comment by lzkelley** [comment]
Hi @Julian I'm thinking about how to handle https://github.com/Julian/jsonschema/issues/343 (and perhaps that's a better place for this question), and your [response](https://github.com/Julian/jsonschema/issues/289#issuecomment-229753142) seemed important.  What do you mean that "relative file references are by definition not portable"?  Doesn't that depend intrinsically on the nature of the project?  For example if the user wants to have a set of schema json-files that will be constructed/installed/used in a runtime-determined directory, as long as the files are always together then relative paths should always work, no?
