### ISSUE TITLE
multipleOf incorrectly raises ValidationError for some floats

### ISSUE THREAD

**Issue by dalehumby** [Julian/jsonschema#320]
In ``_validators.py``, the ``multipleOf`` function incorrectly raises a ValidationError for e.g. 606.67 as not a multiple of 0.01, due to floating point errors.

Our use case is using a schema to ensure that amounts (in Dollars) are in increments of 1 cent ($0.01)

Going through the [code](https://github.com/Julian/jsonschema/blob/master/jsonschema/_validators.py#L119), 
```
quotient = 606.67 / 0.01 = 60666.99999999999
failed = int(quotient) != quotient
failed = 60666 != 60666.99999999999
failed = True
```

One number is a multiple of another number when the quotient is an integer. However, in this case, the quotient is _very close_ to an integer due to floating point representation of those numbers.

The solution I see is: ``instance`` is a multiple of ``db`` if ``quotient`` is close to an integer.

I'm happy to submit a pull request, and first would like to 

1. write a unit tests for this case. Where is the best place for this test?
2. implement an isclose method similar to [math.isclose](https://docs.python.org/3/library/math.html#math.isclose) in Python 3. A [previous commit](https://github.com/Julian/jsonschema/commit/2b9a72273edeac33da7d7f9054f676b0e9f37750) removed something similar. Is there a better way of doing this?

**Comment by Julian** [comment]
I'd recommend not using floats to recommend dollar amounts in that case. You could use a string and a simple regex fairly easily I think?

**Comment by Julian** [comment]
Alternatively you can deserialize your JSON using decimals as well.

**Comment by Julian** [comment]
Closing this out, but lemme know if you disagree.

**Comment by Fufutako** [comment]
If we use Decimal in deserialization we get an error:

```
jsonschema/_validators.py", line 124, in multipleOf
    quotient = instance / dB
TypeError: unsupported operand type(s) for /: 'decimal.Decimal' and 'float```

so multipleof is unusable...

This is how I did to workaround:
```
def multipleOf(validator, dB, instance, schema):
    if not validator.is_type(instance, "number"):
        return

    if isinstance(dB, float):
        if isinstance(instance, float):
            quotient = instance / dB
        else:
            quotient = instance / Decimal(str(dB))
        failed = int(quotient) != quotient
    else:
        failed = instance % dB

    if failed:
        yield ValidationError("%r is not a multiple of %r" % (instance, dB))```

If you want I can submit a merge request. This feature is required for my purpose, however I would prefer to use the official package than a fork.

**Comment by Julian** [comment]
Sounds like you only used a decimal in one of the two places, you need to
have decimals both in your schema and in your instance.

On Jul 13, 2017 13:25, "Fufutako" <notifications@github.com> wrote:

If we use Decimal in deserialization we get an error:

jsonschema/_validators.py", line 124, in multipleOf
    quotient = instance / dB
TypeError: unsupported operand type(s) for /: 'decimal.Decimal' and 'float```

so multipleof is unusable...

This is how I did to workaround:

def multipleOf(validator, dB, instance, schema):
if not validator.is_type(instance, "number"):
return

if isinstance(dB, float):
    if isinstance(instance, float):
        quotient = instance / dB
    else:
        quotient = instance / Decimal(str(dB))
    failed = int(quotient) != quotient
else:
    failed = instance % dB

if failed:
    yield ValidationError("%r is not a multiple of %r" % (instance, dB))```

If you want I can submit a merge request. This feature is required for my
purpose, however I would prefer to use the official package than a fork.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/Julian/jsonschema/issues/320#issuecomment-315050453>,
or mute the thread

**Comment by Fufutako** [comment]
Hi,

Thanks for your reply.

This is an extract from the json-schema.
```
'offer_items': {'items': {'maxProperties': 4,
                          'minItems': 1,
                          'properties': {'description': {'maxLength': 40,
                                                                     'type': 'string'},
                                                'price': {'multipleOf': 0.01,
                                                             'type': 'number'},
                                                'product_id': {'maxLength': 20,
                                                                      'pattern': '[0-9]+',
                                                                     'type': 'string'},
                                                 'quantity': {'type': 'integer'}},
                          'required': ['product_id',
                                            'description',
                                            'quantity',
                                            'price'],
                          'title': 'offer_item',
                          'type': 'object'}
```

it is stored in db and passed directly to validate. So I have no control on dB expected by the schema. How can I make my json-schema to get a Decimal for 'price' ? multipeof is a key word related to number so I don't understand how I can do that. In another hand instance when is deserialized to a float produce floating point error and when it is deserialized to a Decimal raise a TypeError.

**Comment by Julian** [comment]
I presume you deserialize out if your DB using the json module? (You have
to be deserializing using *something*) -- json.loads and friends take
arguments which affect what Python type is used to deserialize JSON
numbers, so you need to pass Decimal to those.

On Jul 13, 2017 14:16, "Fufutako" <notifications@github.com> wrote:

Hi,

Thanks for your reply.

This is an extract from the json-schema.

'offer_items': {'items': {'maxProperties': 4,
                          'minItems': 1,
                          'properties': {'description': {'maxLength': 40,

'type': 'string'},
                                                'price': {'multipleOf': 0.01,
                                                             'type': 'number'},
                                                'product_id': {'maxLength': 20,

'pattern': '[0-9]+',

'type': 'string'},
                                                 'quantity': {'type':
'integer'}},
                          'required': ['product_id',
                                            'description',
                                            'quantity',
                                            'price'],
                          'title': 'offer_item',
                          'type': 'object'}

it is stored in db and passed directly to validate. So I have no control on
dB expected by the schema. How can I make my json-schema to get a Decimal
for 'price' ? multipeof is a key word related to number so I don't
understand how I can do that. In another hand instance when is deserialized
to a float produce floating point error and when it is deserialized to a
Decimal raise a TypeError.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/Julian/jsonschema/issues/320#issuecomment-315060601>,
or mute the thread

**Comment by Fufutako** [comment]
Yes... I use a json field in Postgres and sqlalchemy.JSONField to deal with. I am looking How can I do that with this package. Thanks
