### ISSUE TITLE
Better validation errors for a schema with oneOf/anyOf keywords

### ISSUE THREAD

**Issue by DXist** [Julian/jsonschema#345]
When using schema with oneOf/AnyOf validation message is not helpful for debugging.

I get

```
jsonschema.exceptions.ValidationError: {'is_active': True, ... } is not valid under any of the given schemas

Failed validating 'oneOf' in schema['allOf'][1]:
    {'oneOf': [{'dependencies': {'article': {'properties': {... and my schemas go there
```

It's much better to get the first problem we found during depth first search for validation issue.

Optionally it's possible to provide several specific problems as an exception attribute.

**Comment by Julian** [comment]
Both of those already exist, please see the docs.

It's the context attribute and jsonschema.exceptions.best_match

**Comment by DXist** [comment]
Thank you, got it.

Do you consider using `best_match` inside `validate` helper for better default error handling?

**Comment by Julian** [comment]
They're a bit different from each other. For smaller schemas, sometimes the higher level exception is better than the more specific one, because it shows you all the branches that failed rather than guessing at which one is most relevant.

So I've thought about it, but it's not totally obvious that it's a major improvement in all cases I think, so I've left it as-is for now.
