### ISSUE TITLE
on validation error, path to wrong item is false when "anyOf" is used

### ISSUE THREAD

**Issue by xjlm** [Julian/jsonschema#360]
Hi

when a schema contains a "recursive" structure inside a "anyOf", and there is an error in a related json file deep in the hierarchy, then the validator finds the error but indicates a wrong path:

> python check.py

INFO validate file 'data.json' ... 
ERROR validate file 'data.json' FAIL
ERROR {u'CONTENT': [{u'CONTENT': [{u'CONTENT': [{u'TYPE': u'CHAPTER', u'TITLE': u'chapter_55555'}], u'TYPE': u'CHAPTER', u'TITLE': u'chapter_4'}], u'TYPE': u'CHAPTER', u'TITLE': u'chapter_3'}], u'TYPE': u'CHAPTER', u'TITLE': u'chapter_2'} is not valid under any of the given schemas *** deque([u'CONTENT', 0, u'CONTENT', 0])

Note that the online validator https://json-schema-validator.herokuapp.com finds many errors but at least indicates the error concerning the string being too long and its path

see attached files schema.json and data.json

**Comment by xjlm** [comment]
[BUG_VALIDATION.zip](https://github.com/Julian/jsonschema/files/1298746/BUG_VALIDATION.zip)

**Comment by xjlm** [comment]
Oupps sorry, its seems that I really handle "AnyOf" a wrong way...

**Comment by xjlm** [comment]
[BUG_VALIDATION.zip](https://github.com/Julian/jsonschema/files/1298964/BUG_VALIDATION.zip)

**Comment by xjlm** [comment]
Note that when the schema is written without "anyOf", then the error and its path are perfectly reported.

**Comment by Julian** [comment]
Hi.

I'm not sure I fully follow what you're calling the bug, but I *think* you're just referring to the fact that `jsonschema` will not recurse into an anyOf (even one that only has one branch) when reporting an error -- doing so (in the general case) doesn't make too much sense, because there are multiple places in the instance that were wrong, one for each branch of the anyOf.

Please have a look at http://python-jsonschema.readthedocs.io/en/latest/errors/#best-match-and-relevance though, which do try to guess which error you probably want to see.

**Comment by xjlm** [comment]
Hi.

Unfortunately the "best match" cannot help, as I only get 1 error. The error message seems actually to be OK, und unfortunately not very helpful.

In the example (data.son), there is a string of length 13 ("chapter_55555"), although the schema imposes a maxLength of 10.
What I am expecting is something like this (as in  https://json-schema-validator.herokuapp.com)

...
"instance" : {
                    "pointer" : "/CONTENT/0/CONTENT/0/CONTENT/0/CONTENT/0/CONTENT/0/TITLE"
                  },
                  "domain" : "validation",
                  "keyword" : "maxLength",
                  "message" : "string \"chapter_55555\" is too long (length: 13, maximum allowed: 10)",
                  "value" : "chapter_55555",
                  "found" : 13,
                  "maxLength" : 10
                } ]
              }
...

which clearly reports the error, even if there are many other errors (noise) reported concerning "anyOf".

But jsonschema does not report at all somethings related to the string "chapter_555555" being to long.

Sincerely,

xjlm

**Comment by Julian** [comment]
Still not quite sure what you mean, did you read that doc page? `best_match` gives you exactly that kind of information (and for your case it gives you exactly that error).

**Comment by xjlm** [comment]
Hi,

Yes, you're perfectly right, I did not try "best_match" ... sorry.
So now I get as you said this error message:

ERROR u'chapter_55555' is too long *** deque([u'CONTENT', 0, u'CONTENT', 0, u'CONTENT', 0, u'CONTENT', 0, u'CONTENT', 0, u'TITLE'])

But unfortunately I've just try this 'best_match' with an other schema (with an "anyOf" containing 2 items) and another json data, and the error message seems NOT to be OK to be:

> python check.py

ERROR u'DATA' is not one of [u'CHAPTER'] *** deque([u'CONTENT', 0, u'CONTENT', 0, u'CONTENT', 0, u'CONTENT', 0, u'CONTENT', 0, u'TYPE'])

I am waiting:

ERROR u'data_5555555' is too long *** deque([u'CONTENT', 0, u'CONTENT', 0, u'CONTENT', 0, u'CONTENT', 0, u'CONTENT', 0, u'TITLE'])

What do you think about it ?

Sincerely,

xjlm

PS: check.py, data.json and schema.json in BUG_VALIDATION2.zip 
PPS: please feel free to close the ticket if you think I am wrong

[BUG_VALIDATION2.zip](https://github.com/Julian/jsonschema/files/1306521/BUG_VALIDATION2.zip)

**Comment by Julian** [comment]
Sounds like your data has multiple errors then, or that it has one error on
each branch of the anyOf, so you're getting the error from the other branch
which is equally "wrong".

Unfortunately I can't really spend much time helping you troubleshoot,
there's an IRC channel and a mailing list if you need some help, but unless
you think there's a bug or some missing functionality I'm not sure I can do
anything more here, my guess is that you just need to have another look at
the documentation and play a bit with what exists?

On Sep 15, 2017 9:45 AM, "xjlm" <notifications@github.com> wrote:

Hi,

Yes, you're perfectly right, I did not try "best_match" ... sorry.
So now I get as you said this error message:

ERROR u'chapter_55555' is too long *** deque([u'CONTENT', 0, u'CONTENT', 0,
u'CONTENT', 0, u'CONTENT', 0, u'CONTENT', 0, u'TITLE'])

But unfortunately I've just try this 'best_match' with an other schema
(with an "anyOf" containing 2 items) and another json data, and the error
message seems NOT to be OK to be:

python check.py

ERROR u'DATA' is not one of [u'CHAPTER'] *** deque([u'CONTENT', 0,
u'CONTENT', 0, u'CONTENT', 0, u'CONTENT', 0, u'CONTENT', 0, u'TYPE'])

I am waiting:

ERROR u'data_5555555' is too long *** deque([u'CONTENT', 0, u'CONTENT', 0,
u'CONTENT', 0, u'CONTENT', 0, u'CONTENT', 0, u'TITLE'])

What do you think about it ?

Sincerely,

xjlm

PS: check.py, data.json and schema.json in BUG_VALIDATION2.zip
PPS: please feel free to close the ticket if you think I am wrong

BUG_VALIDATION2.zip
<https://github.com/Julian/jsonschema/files/1306521/BUG_VALIDATION2.zip>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Julian/jsonschema/issues/360#issuecomment-329787127>,
or mute the thread

**Comment by xjlm** [comment]
closed because it may be an user error
