### ISSUE TITLE
regex does not work in string format

### ISSUE THREAD

**Issue by arindamchoudhury** [Julian/jsonschema#396]
Hi,
Regex pattern is not working for string format:

```
from jsonschema import FormatChecker, validate

schema = {
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "required": ["email", "account"],
    "properties": {
        "email": {"type":"string", "format":"email"},
        "account": {"type": "string", "format": "(?![0-9-])[a-z0-9-]{6,63}(?<!-)$"}        
    }
}

data = {
    'account': '0--jcm-test',
    'email': 'test@ackstorm.com',
}

validate(data, schema, format_checker=FormatChecker()) 
```

**Comment by Julian** [comment]
That's not the syntax for applying a regex.

The pattern validator is how you do that.

**Comment by arindamchoudhury** [comment]
schema = {
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "required": ["email", "account"],
    "properties": {
        "email": {"type":"string", "format":"email"},
        "account": {"type": "string", "pattern": "(?![0-9-])[a-z0-9-]{6,63}(?<!-)$"}        
    }
}

This also fails

**Comment by Julian** [comment]
Sorry, I don't know what you mean by "fails". Please always include code, a traceback if you get one, or otherwise a description of what you expected to happen and what happened instead. http://sscce.org/ is generally good reading.

Also, I'll try to see if I can help you troubleshoot, but please use the bug tracker for cases where you suspect a bug in jsonschema -- one here is very unlikely, this area of jsonschema is well tested. It's a lot more likely that you're still doing something wrong according to the spec. I'd encourage you to try e.g. matching your pattern directly against inputs you expect to pass or fail.

**Comment by arindamchoudhury** [comment]
I will explain it better here:

```
In [1]: import re

In [2]: pattern = re.compile(r"(?![0-9-])[a-z0-9-]{6,63}(?<!-)$")

In [3]: bool(pattern.match('-test-ing'))
Out[3]: False
```

but same pattern and string do not raise a validation error:

```
from jsonschema import FormatChecker, validate

schema = {
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "required": ["email", "account"],
    "properties": {
        "email": {"type":"string", "format":"email"},
        "account": {"type": "string", "pattern": "(?![0-9-])[a-z0-9-]{6,63}(?<!-)$"}        
    }
}

data = {
    'account': '-test-ing',
    'email': 'test@email.com',
}

print validate(data, schema, format_checker=FormatChecker()) 
```

the above code outputs none.

**Comment by Julian** [comment]
You used `re.match`, which isn't a thing you really should ever use in Python. In JSON Schema (and with `re.search`, which is what you generally should use), regexes are not anchored, and your pattern matches.

**Comment by Julian** [comment]
Going to close this out, but if you're still having trouble, the mailing list might be worth a shot.
