### ISSUE TITLE
New jsonschema release cut/version coming up?

### ISSUE THREAD

**Issue by JonKohler** [Julian/jsonschema#405]
Hey QQ - We're running jsonschema 2.5.1 in one of our products and looking to do a bit of a tech refresh. I see 2.6.0 is out/stable as of Feb 2017, but do see a lot of commits into master since that time. We're using draft4 schema, and aren't looking at draft 6/7 at all yet, as this particular product is using swagger/openapi 2.0 only. 

Is there a milestone that we're trending to on this project to cut (whatever the next version is going to be?) Or does this even matter for draft4 use cases?

**Comment by Julian** [comment]
Hi!

So on master (and to be released) the only draft4-relevant change is the new `TypeChecker` interface, which lets you do more than just `isinstance` checks on JSON types. If that's something interesting to you it'll be out imminently, but yeah won't see a release until draft-06 changes are merged as well, just because I don't have enough time to separate them fully. The draft-06 stuff is on a branch (called draft-06) which I'd definitely appreciate feedback on, but if you're not actually using Draft 6 likely isn't relevant to you.

**Comment by JonKohler** [comment]
ok great! thanks for the swift response, ill stick with 2.6.0 ga for now.

**Comment by Julian** [comment]
Sure thing! Let me know how it goes.
