### ISSUE TITLE
ImportError: cannot import name 'validate'

### ISSUE THREAD

**Issue by hqkhan** [Julian/jsonschema#483]
Hi. Not sure what is going on here as I'm getting an import error from the get go when trying to import `jsonschema`. Here is a snapshot:

![image](https://user-images.githubusercontent.com/22674069/47882630-8fe02d80-de00-11e8-986f-8db58a257d76.png)

What am I missing here?

**Comment by Julian** [comment]
You named a file json.py (and possibly also jsonschema.py), which is
shadowing actually importing those modules.

**Comment by hqkhan** [comment]
Thank you for showing me how big of a goof I am. Fixed the issue. 

Would you mind letting me know how you figured out that the name of the file was the problem?

**Comment by Julian** [comment]
:) no worries.

I really just read the traceback from top to bottom to be honest, along
with knowing that typically when you see an ImportError there it means you
have a circular import (which Python is really bad at reporting, it should
really explicitly say that the kind of import error that occurred is due to
circularity).
