### ISSUE TITLE
Support file globs in CLI -i

### ISSUE THREAD

**Issue by bquinn** [Julian/jsonschema#503]
It would be great if I could say
`jsonschema -i tests/*.json myschema.json`

The shell resolves the glob to expand this into
`jsonschema -i tests/1.json tests/2.json [...] myschema.json` which fails.

Currently I can work around this with a `find` incantation:
`find tests/*.json -exec jsonschema -i {} myschema.json \;`

But as this spawns a new Python and jsonschema instance for each file it is obviously a lot slower.

**Comment by Julian** [comment]
Hey, thanks.

FWIW personally I always think this is a shell gap (which isn't to say that I'm not open to fixing it anyhow :)

But, you *can* do this, the syntax is just a bit arcane if you haven't done it before. E.g., your first glob should be `jsonschema tests/*.json(e:REPLY=-i'$REPLY':) myschema.json`.

And as for your second one, yeah, well, everyone should use GNU Parallel :), which solves that one.

But yeah the issue here is that it's a bit tricky or error prone to handle a thing like <instances, everything but the last element> <schema>. At the minute IIRC jsonschema's CLI uses argparse, but click might make it easier there.

**Comment by Julian** [comment]
I think it's unlikely I myself would implement this -- I suppose I'm happy to see a PR if anyone finds this and is suitably motivated, although beforehand likely we should move to click anyhow, and then this would potentially be an incremental improvement on top.

**Comment by fmagin** [comment]
I am not sure in which shell the command `jsonschema tests/*.json(e:REPLY=-i'$REPLY':) myschema.json` is supposed to work in, but `GNU bash, version 5.0.18(1)` results in ```bash: syntax error near unexpected token `('```.

There is a [stackexchange post](https://unix.stackexchange.com/a/445522/407102) that lists the ways to achieve this with different shells like `bash`, `zsh`, `fish` and `ksh93`

**Comment by Julian** [comment]
It's zsh pre-`P`, but that's a good post.
