### ISSUE TITLE
Incorrect SchemaError for enum schema with unique elements

### ISSUE THREAD

**Issue by Zac-HD** [Julian/jsonschema#529]
```python
# Draft7 for convenience; the same applies to 3, 4, and 6.
# We can have a unique list of things that compare equal, e.g. this works:
jsonschema.Draft7Validator.check_schema({'enum': [False, 0.0]})

# But wrap them in a one-element list, and we get a `SchemaError` instead!
jsonschema.Draft7Validator.check_schema({'enum': [[False], [0.0]]})
```

There are IMO two bugs here:

1. JSON values are being tested for equality using Python object semantics, rather than comparing them as JSON (e.g. via a canonical encoding).

2. The json-schema specification says 

        The value of this keyword MUST be an array.
        This array SHOULD have at least one element.
        Elements in the array SHOULD be unique.

   Validation therefore ought to allow schema authors to use empty or non-unique arrays, because the RFC 2119 definition of `SHOULD` explicitly permits ignoring such clauses after considering the circumstances.

**Comment by Zac-HD** [comment]
I also just want to say thanks for the `jsonschema` library - the interface is easy to use, and the fantastic error messages when I misused or misunderstood something have saved *so much* time debugging.

I stumbled over this when [a build failed](https://travis-ci.org/Zac-HD/hypothesis-jsonschema/jobs/497373384) for [my `hypothesis-jsonschema` library](https://github.com/Zac-HD/hypothesis-jsonschema), which generates arbitrary instances matching a schema for testing.  In this case it was also generating arbitrary schemas!

**Comment by Julian** [comment]
Woohoo, thanks for writing the hypothesis thing, been on my list for awhile but never gotten to it (oddly got to it for [protobuf](https://github.com/Julian/hypothesis-protobuf) first).

That first one does look like a bug, though `jsonschema`, despite its name, doesn't deal at all with JSON, it does use Python semantics and objects, and just avoids the Python behavior when needed (because it'd clash with JSON). E.g., it evades `issubclass(bool, int)` for doing type checks that JSON Schema defines. Seems like `uniqueItems` is likely missing the same sort of evasion.

The second one also looks like a bug but not here :), because all `jsonschema` does is use the official meta schemas. E.g. here for [enum](https://github.com/Julian/jsonschema/blob/master/jsonschema/schemas/draft7.json#L139-L144) you'll see that despite the language of the spec, it does refuse any instances with non-unique items (or an empty array). That metaschema is yeah just the official one essentially (copied from e.g. https://github.com/json-schema-org/json-schema-spec/blob/draft-07/schema.json#L139-L144). The right thing to do here then is probably for us to file a bug in the spec repo, and then once we merge it there `jsonschema` will just stop raising those.

> I also just want to say thanks for the `jsonschema` library - the interface is easy to use, and the fantastic error messages when I misused or misunderstood something have saved _so much_ time debugging.

Thank you! That's very very good to hear :) particularly about the error messages. There's still lots to do to make them even better I suspect, but yeah glad they helped.

**Comment by Julian** [comment]
OK, have pushed a local fix for the metaschema bugs here... Gonna have to set aside some time to start moving tests upstream to help us move it into the spec repo too.

**Comment by Julian** [comment]
Hee hee I also just realized that the second bug is likely impossible to fix for arbitrary types, so will need to think about what to do about that.

**Comment by Zac-HD** [comment]
I just checked this, and it's fixed by `jsonschema==3.0.2` 🎉

**Comment by Julian** [comment]
I mentioned this briefly on https://github.com/json-schema-org/json-schema-spec/issues/717#issuecomment-1299112660 but just for archaeological purposes, this change was just partially "backed out" for drafts 3 and 4 where indeed the original behavior (MUST) was correct, those drafts contain stronger language. It's definitely correct on newer ones though (so thanks again for filing it!)

**Comment by erohmensing** [comment]
@Julian thanks for the "for archeological purposes", rest assured it's worth adding as people still run into this strange mismatch years later 😄
