### ISSUE TITLE
Add support for validating the schema only once

### ISSUE THREAD

**Issue by wilbertom** [Julian/jsonschema#546]
Hey all, really nice library, thank you! It has saved me tons of time on a project I'm working on.

We have some feedback after adapting it for our use case. We wanted to validate the JSON schema once instead of every time we call `jsonschema.validate`. Our concern wasn't so much the performance of validating the schema every time, we just wanted to validate the schema before starting our web server.

Here is some source code of how we wrap `jsonschema`:

```python
import json
import jsonschema
import jsonschema.validators
from .exceptions import SchemaError


class JsonSchema(object):

    def __init__(self, filename):
        self._filename = filename

        with open(self._filename) as f:
            try:
                self._value = json.load(f)
            except ValueError as e:
                raise SchemaError(e.message)

            self._validator = jsonschema.validators.validator_for(
                self._value
            )(self._value)

        # make sure the schema is valid just once now we don't have to validate
        # it every single time how jsonschema.validate does
        try:
            self._validator.check_schema(self._value)
        except jsonschema.SchemaError as e:
            raise SchemaError(e.message)

    @property
    def value(self):
        return self._value

    def valid(self, instance):
        try:
            self._validator.validate(instance, self.value)
            return True

        except jsonschema.ValidationError:
            return False
```

With this we will have some global schema:

```
schema = JsonSchema('schema.json') # raises an error if schema is invalid before starting app

web_app.run()
```

The documentation gave us enough hints to get this done but it did take some digging. I would like to:

* Export `validator_for` in the jsonschema module, so `jsonschema.validator_for` works. Making it part of the public API.
* Add a documentation example of doing this.

If you think this isn't worthwhile feel free to close this issue, no feelings hurt.

Thank you.

**Comment by Julian** [comment]
Hi! Thanks for the ticket. You're the second person to say that finding the validator API was difficult, so I am definitely open to improvements -- something must be misaligned for people to be having difficulty so happy to hear what could be better of course! On the specific suggestions:

> Export validator_for in the jsonschema module, so jsonschema.validator_for works. Making it part of the public API.

Why does this signal to you that things are any more public? Mostly it was an old mistake that `validate` lives in the global package in the first place, owing back to ancient history when `jsonschema` was a single module -- these days if I was older or wiser, even `validate` would not be exposed there, since generally `__init__.py`s should be empty, but it's left exposed for the old backwards compatibility reasons. But I'd be much happier *deprecating* using `jsonschema.validate` as is without importing `jsonschema.validators` at this point than adding even more things there I think :/

Because of the first time I got this feedback, the docstring for validate itself now says something like "probably if you want to do this more than once, you want `Draft7Validator(schema)` instead. In your search, did you find and read https://python-jsonschema.readthedocs.io/en/stable/validate/#jsonschema.validate ?

Certainly that page could still use further improvements, but curious to hear.

And yeah definitely appreciate the usability report! Definitely up for further improvements.

**Comment by Pluckerpluck** [comment]
> Why does this signal to you that things are any more public?

Many libraries use `__init__.py` to export "key" components of their library so the front end simply involves importing the package name and not every single module that they need. i.e. the things they define as the public facing API. The idea that `__init__.py` should be empty just isn't backed up practically. I mean, just look at something like [numpy's __init__.py](https://github.com/numpy/numpy/blob/master/numpy/__init__.py), or [requests](https://github.com/kennethreitz/requests/blob/master/requests/__init__.py), or [Scrapy](https://github.com/scrapy/scrapy/blob/master/scrapy/__init__.py) (they specifically declare top level shortcuts), or [Flask](https://github.com/pallets/flask/blob/master/flask/__init__.py). They import (and thus export) everything that they want to provide easy access to.

Not every library does it. But **a lot** do.

**Comment by Julian** [comment]
I don't maintain those projects but I do maintain this one :)

I agree there certainly are others who don't hold the same opinion.

**Comment by Pluckerpluck** [comment]
Oh don't get me wrong. I have absolutely no issue with the layout of the project. It's not like the minuscule extra effort of importing `jsonschema.validators` is an issue in the slightest.

I was just responding to your question about why exports in `__init__.py` may appear more "public" by presenting some of the most popular Python libraries and the practices they use. I think it comes down a lot to autocomplete within IDEs and the more modern practices of importing module namespaces rather than specific functions:

i.e. `import numpy as np; np.some_function()`, rather than `from numpy import some_function(); some_function()`.

because then typing `np.` into your IDE lists all the functions you can access, and smart autocompletes will often present exactly what you'll want as the first option.

-----------

But as you said, you maintain this project, so you can do whatever you like! :P As I said, this really isn't a problem. I'm going to use the library regardless, and I'm very happy it exists, and if I find any issues with it during my use I'll contribute back to this project.

I only replied in the first place because I too had wondered about the idea of exposing `validator_for` in `__init__.py` when I did pretty much the **exact** same thing as OP here (wrap jsonschema with a `Schema()` object) for my project.

**Comment by wilbertom** [comment]
Hey @julesjulian, like @Pluckerpluck  mentioned, thinking that adding `validator_for` to `__init__.py` makes it part of the API is just an assumption based on experiences with other libraries. I think it is a implicit agreement between some Python programmers. Another reason is the documentation, since everything I read only referenced `jsonschema` and `jsonschema.exceptions`, I thought these were the public API. Although I just noticed that [one page](https://python-jsonschema.readthedocs.io/en/stable/creating/#creating-validation-errors) does mention the `jsonschema.validators` module so that is my bad.

So here is what the documentation says:

> If you know you have a valid schema already, especially if you intend to validate multiple instances with the same schema, you likely would prefer using the IValidator.validate method directly on a specific validator (e.g. Draft7Validator.validate).

The way I interpret this is, if you can assume the schema is valid i.e, it is an invariant that the schema is valid, then you can skip validating the schema and you should especially do this if you are going to validate multiple instances with the same schema. 

In my use case, the schema being valid isn't an invariant but, I want to make it so by validating once, during application start up. So I clicked on the `IValidator.validate` link and get taken to this example:

```python
>>> schema = {"maxItems" : 2}
>>> Draft3Validator(schema).validate([2, 3, 4])
Traceback (most recent call last):
    ...
ValidationError: [2, 3, 4] is too long
```

And I think: this isn't what I need because I also need to make sure the schema is valid at least once and at this point I just jumped to the source code directly instead of finishing reading the documentation like I should of. Had I done it, I would of found the references to `check_schema`

Now of course someone else might interpret the documentation another way. I just want to add my thoughts in case this does come up again, you might want to rewrite that paragraph a little bit. Honestly though I think its OK how it is.

**Comment by wilbertom** [comment]
I'll let you close this comment since I think its OK.

**Comment by Julian** [comment]
Cool! @wilbertom thanks for the feedback, definitely useful to hear how you read those!

Will close for now but more than happy to hear feedback from anyone else here as well.
