### ISSUE TITLE
Enable strict mode: Throw an error if a property is unknown

### ISSUE THREAD

**Issue by MatinF** [Julian/jsonschema#597]
Hi there,

We have a fairly large schema in which we need to ensure that no "extra" properties are included.

This can of course be done via `additionalProperties: false`. However, we also have a lot of dependency fields, meaning that we need to add a lot of convoluted `patternProperties` to account for all the dynamic fields that may be added.

To avoid this, we were hoping to be able to use a "strict" mode in the Python jsonschema. Basically, this would throw an error when the form data contains a property that is not included in the schema. 

Other JSON Schema editors like ruby-json-schema and react-json-schema-form seem to have a similar feature, but we've not be able to find it in jsonschema. Did we simply miss it or is it a deliberate decision to not include this?

Best,
Martin

**Comment by Julian** [comment]
Hi! Thanks for the question.

So... I think "strict modes" are an antipattern (for many reasons, some of which I've elaborated on in earlier tickets so will not type them out again unless need be) so not having something called "strict mode" is certainly intentional.

That being said -- there's two things here. One is that the specification is itself trying to struggle with this problem, and has been for.. essentially the entire time I've been involved, so like 7 years. Namely -- given a schema `foo`, how do you *externally* from foo say no additional properties are allowed beyond what it defines. There's been progress there on the spec side, and I haven't yet fully read draft 8 so it's possible I'm wrong, but still nothing specifically concrete has landed, but I suspect it will come.. sooner rather than later.

Now, beyond the spec, the question becomes how much does a JSON Schema library (say this one :) do to *smooth over* the holes / gaps / inefficiencies of the spec -- which tends to be subjective obviously. Concretely -- the right way to think about this problem and others IMHO is schema transformations. And the relevant one here is (in scaffolded pseudocode):

```
def noAdditionalProperties(schema):
    -> newSchema that disallows any but the properties defined by schema
```

at which point solving your problem is just changing `validate(instance, schema)` to `validate(instance, noAdditionalProperties(schema))`. And implementing that transform programmatically should be super straightforward. The "obvious" `allOf[schema, {"additionalProperties": false}]` does not work, for spec reasons alluded to above, but once you're in Python and can "look around" the schema programmatically, you can collect the right new schema.

So yeah *if* `jsonschema` were to implement this behavior, that'd be how it'd do it. Now whether said transformation should be part of this library... yeah that's back to being subjective I think -- in this case it's probably reasonable to add given the long history of wanting it, but the reason it hasn't existed is simply that I've just said in the past "if it's so useful it seems like someone should just create a utility library with a bunch of useful schema transformations of that signature" (and there are others, and Seep was a thing I tried to demonstrate myself there).

So I'm really still inclined to think that's the right solution to this. But, I'm open to being convinced!

**Comment by MatinF** [comment]
Thanks a lot for the clarification Julian - we'll dicsuss it in the team internally. Appreciate the time you took to comment.
