### ISSUE TITLE
CLI parameters: jsonschema schema.json data.json

### ISSUE THREAD

**Issue by cweiske** [Julian/jsonschema#620]
The commandline interface parameters are a bit strange:

    $ jsonschema -i data.json schema.json

It would be easier to use (without needing to read the help) if the parameters would be in a different order:

    $ jsonschema schema.json data.json

**Comment by Julian** [comment]
There are decent reasons it works the way it does, so that you can validate multiple instances at the same time. The order isn't significant, so if you want to list the schema first that does work AFAIK, but yes you need to specify `-i`.

I don't think it's a huge burden to read `jsonschema --help` if it isn't initially obvious.

Happy to discuss further, especially if you want to show examples of how other JSON Schema CLIs function, but yeah not sure this one is as obviously better to me.

(Especially considering the current interface would need to stay for backwards compat).

Closing just for cleanliness, but comments of course welcome.

**Comment by cweiske** [comment]
Multiple files can be validated by passing multiple file names at the end:

```
$ jsonschema schema.json data1.json data2.json
```

Generally, options should be optional. "jsonschema schema.json" is of no use, because you need to specify at least one file in the `-i` option, which makes the "option" not optional anymore.

Other tools:

```
$ xmllint --schema data.xsl data1.xml data2.xml
$ phpcs --standard=rules.xml code1.php code2.php
$ yamllint file1.yaml file2.yaml
```

**Comment by Julian** [comment]
I know it *can* be disambiguated of course, like I said though, it's not obvious that's better to me.

All the ones you mentioned do not mix heterogeneous arguments, so if anything they seem to me like validation of the current way?
