### ISSUE TITLE
Prevent schema issues from causing validation to be skipped

### ISSUE THREAD

**Issue by recvfrom** [Julian/jsonschema#658]
I recently encountered an issue similar to what was described in #268 - there was a mistake in my schema that caused parts of the validation to be skipped.  For example, a schema author likely intends for the following to look for an integer, but it effectively performs no validation:
```
{
"typ": "integer"
}
```
The documentation states that `validate() will first verify that the provided schema is itself valid`, so I was surprised by this.  I know very little about the jsonschema format, so maybe that is a valid schema, but it seems error-prone to allow unrecognized keywords in the schema (apart from where it makes sense, like in a `properties` section).  I wonder how many people have errors like this in their schemas but don't realize it?

Anyway, is there anything that can be done to help prevent these types of errors from occurring?  How do most people ensure that their schemas is free from this type of defect?

I'd be happy to submit a PR that incorporates any best practices into the example documentation.

Thank you!

**Comment by Julian** [comment]
That's a valid JSON Schema by the spec yeah, and it indeed does nothing.

> Anyway, is there anything that can be done to help prevent these types of errors from occurring? How do most people ensure that their schemas is free from this type of defect?

The best advice I have is still "schemas are not replacements for unit tests". Your unit tests should catch that you've misspelled type, since the one you have verifying that invalid things don't get through won't fail.

But yes this is definitely a common occurrence (this library though is just doing what the spec says it should).

**Comment by recvfrom** [comment]
@Julian Thanks for the quick response!

Would validation of the schema against one of the meta-schemas mentioned at https://json-schema.org/specification.html catch these types of issues?  If not, would it be worth raising this issue to the people that create the spec / meta-schemas to see whether this is something that should be changed?  I imagine many people are using json schema validation for API input validation, so it seems like you'd want to make it as difficult as possible for these schema errors to go unnoticed and potentially expose web services to exploitation.

**Comment by Julian** [comment]
It wouldn't, it's exactly the metaschemas that define this behavior.

Basically you can't really support both extensibility and this -- if the metaschemas were closed by default someone couldn't come add new validators to JSON Schema that weren't part of the spec.

(Which is something this library supports too).

**Comment by recvfrom** [comment]
If someone wanted to add new schema keywords and new corresponding validators, couldn't they also just create a new meta-schema that "allows" the keywords they added?

Taking a step back, I think there's another possible approach to this.  For the API input validation that I'm doing, I expect every part of a json being validated to map to a corresponding schema validation rule.  Is there a way to have the validation library raise an exception if this is not the case, effectively preventing partial json validation?

Thanks again!

**Comment by Julian** [comment]
> If someone wanted to add new schema keywords and new corresponding validators, couldn't they also just create a new meta-schema that "allows" the keywords they added?

No because schemas don't inherit, they just compose -- you can't take the metaschema and mutate it -- it either allows additional properties or it does not. In this case, it does.

> I expect every part of a json being validated to map to a corresponding schema validation rule.

I don't know that I understand what you mean here. It sounds like you've seen the issue ticket there that if what you want is to extend the metaschema to disallow additional validators you can, and then catch this error -- maybe that's what you're looking for then?

If not, happy to keep helping but would be good to move this to the [slack for the spec](https://json-schema.slack.com/) or some other medium so that we can keep the issue tracker for bugs if that's ok.

**Comment by recvfrom** [comment]
Sounds good, thank you
