### ISSUE TITLE
Schema validation issue on pattern mis-match

### ISSUE THREAD

**Issue by cmg1986** [Julian/jsonschema#667]
I have swagger yaml files which is having schems definition, properties with regex.
If there is an issue with json spec file then it thows an error like "is not valid under any of the given schemas" but doesnt show which specific properties having pattern match issue or something else.

Is there any way to show specific error like patter didnt match with that properties or something because its little difficult to parse long spec file which its not matching on generic error.

using below code to validate ..
```
    def set_defaults(validator, properties, instance, schema):
        if (('type' not in schema['properties']) or
                (('type' in instance) and (schema['properties']['type']['default'] == instance['type']))):

            for property, subschema in six.iteritems(properties):  # pylint: disable=redefined-builtin
                if 'default' in subschema:
                    instance.setdefault(property, subschema['default'])
        for error in validate_properties(validator, properties, instance, schema):
            yield error

    return jsonschema.validators.extend(validator_class, {'properties': set_defaults})


DefaultsEnforcingDraft4Validator = extend_with_set_default(Draft4RequestValidator)
```

Using connexion 2.6.0
openapi 3.0.0

**Comment by Julian** [comment]
Hi. Sorry you're having trouble.

Please have a read through the [documentation on `ValidationError`s](https://python-jsonschema.readthedocs.io/en/stable/errors/) which covers the information available for any error.

It sounds like you may want one of the things there and that you're dealing with some compound validator.

If you have further trouble, please ask on either the JSON Schema slack or StackOverflow so that we can keep the issue tracker for bugs or feature requests.
