### ISSUE TITLE
MultipleOf validation Bug

### ISSUE THREAD

**Issue by noelwilsondel** [Julian/jsonschema#687]
Hello,

Firstly thanks for this library it's really useful, we have noticed some unusual behaviour on version 3.2.0 validation using `multipleOf` constraint for example:

```
>>> from jsonschema import validate
>>> schema = {
...     "type" : "object",
...     "properties" : {
...         "test" : {"type" : "number", "multipleOf": 0.001},
...     },
... }
>>> # This should be valid but raises validation error
>>> validate(instance={"test" : 0.95}, schema=schema)
```

Some other things we noticed using the above value this passes:
```
>>> # This is valid
>>> validate(instance={"test" : 0.01}, schema=schema)
>>> # This is valid
>>> validate(instance={"test" : 0.1}, schema=schema)
>>> # This is invalid
>>> validate(instance={"test" : 0.95}, schema=schema)
```

**Comment by Julian** [comment]
Hi! Glad to hear.

Sorry you're having trouble -- this issue is just the way float division works -- have a look at some [historical related issues](https://github.com/Julian/jsonschema/search?q=multipleof&type=Issues).

If you don't want float division, use something with the precision you want, e.g. `decimal.Decimal`, when deserializing your JSON.

**Comment by Julian** [comment]
Hope that helps with some ideas, obviously happy to follow up.

**Comment by jwnwilson** [comment]
@Julian We're attempting the `parse_float=decimal.Decimal` route thanks for the suggestion
