### ISSUE TITLE
Can't use validators as mock spec in Python 3.8

### ISSUE THREAD

**Issue by EpicWink** [Julian/jsonschema#695]
In Python 3.8, the object you pass as the `spec` argument to `unittest.mock.Mock` has its attributes iterated over. One of those attributes is `DEFAULT_TYPES`, which when accessed will raise `jsonschema.validators._DontDoThat`. This is not an issue in previous version of Python.

This will be solved by #681.

* `jsonschema`: 3.2
* Python: 3.8.3

```python
from unittest import mock
import jsonschema
mock.Mock(spec=jsonschema.Draft7Validator)
```

Current solution:
```python
import sys, jsonschema
Draft7Validator = jsonschema.Draft7Validator
if sys.version_info >= (3, 8):
    from importlib import metadata
    if int(metadata.version("jsonschema").split(".")[0]) < 4:
        class _Override(jsonschema.validators._DefaultTypesDeprecatingMetaClass):
            DEFAULT_TYPES = None
        class Draft7Validator(jsonschema.Draft7Validator, metaclass=_Override):
            pass
```

**Comment by Julian** [comment]
Hi!

Yeah, if you're OK waiting for #681 that's certainly a solution I'm happy with -- I'm not terribly inclined to support this kind of thing in general though -- iterating over a Python object's attributes isn't really a thing. I'd expect `mock` to basically do `try/except Exception` when doing so (even though yeah not great to do it anyhow, but obviously I know why it's doing it). Not sure why it isn't doing that but may be worth bringing up upstream.

Overall as well I don't particularly recommend using `mock` personally -- if it works great, but it's in the "not directly supported box" for these kinds of things -- beyond #681 I can't guarantee in general that objects are able to have their attributes iterated without side effects.

Closing, but happy to discuss further if need be -- otherwise keep an eye on #681, though I likely won't close it until #613 lands for `jsonschema 4.0`.
