### ISSUE TITLE
result of running CLI without options?

### ISSUE THREAD

**Issue by sloanlance** [Julian/jsonschema#706]
If I run the jsonschema CLI with the name of a schema file, but I don't give any options, it doesn't seem to do anything.  That is:

```sh
jsonschema schema_file.json
```

There's no output.

What is it doing, if anything?

**Comment by Julian** [comment]
Hi. With no instances specified, essentially just validating your schema.

**Comment by sloanlance** [comment]
What do you think of having it validate stdin against the schema if no `-i` option is given?

If you like that idea, I'm interested in implementing this feature and opening a PR back to this repo.

**Comment by Julian** [comment]
Thanks for the offer!

That's actually already implemented :), it's just not released yet. It's on master though. Part of the reason for the release delay is I'd love some slightly further improvements to the CLI before a release, but I may not get the time, and may just have to push it out.

But certainly if you're offering to help it would be more than appreciated!

**Comment by sloanlance** [comment]
I don't know what time frame you have in mind, but I'd be happy to take a look at the CLI issues (or maybe others) and see whether I can help.  Can you tell me links to the issues you had in mind?

**Comment by Julian** [comment]
That'd be amazing! The time frame is likely less of a big deal, as unfortunately is usual at this point, at some point either enough time will go by that I'll have to release without the improvements and then add them in when they get done, or the release will keep dragging :/

As for the concrete ones, so there are definitely some (underspecified) issues that I have in mind -- #672 is one. But I think more important than adding even more output renderers is essentially cleaning up the one new one that was added. Specifically, here's some example output from the new `pretty` renderer:

```
⊙  printf '7' | jsonschema --output pretty <(printf '{"minimum": 9, "multipleOf": 3, "not": {"const": 7}}')                                                                        julian@Air
===[ValidationError]===(<stdin>)===

7 is less than the minimum of 9

Failed validating 'minimum' in schema:
    {'minimum': 9, 'multipleOf': 3, 'not': {'const': 7}}

On instance:
    7
-----------------------------
===[ValidationError]===(<stdin>)===

7 is not a multiple of 3

Failed validating 'multipleOf' in schema:
    {'minimum': 9, 'multipleOf': 3, 'not': {'const': 7}}

On instance:
    7
-----------------------------
===[ValidationError]===(<stdin>)===

{'const': 7} is not allowed for 7

Failed validating 'not' in schema:
    {'minimum': 9, 'multipleOf': 3, 'not': {'const': 7}}

On instance:
    7
-----------------------------
```

where some things that rub me a bit wrong visually are:

* the width of the ascii dividers (right now it's a bit arbitrary)
* not using unicode box characters
* needing a bit of vertical space between each error
* the fact that, though it's not obvious there, in the exception message, what's there is reprs of Python objects. Even though usually that's what I *want* shown because jsonschema normally deals with Python objects, not JSON, here that's *not* the case -- here in fact the reverse is true -- the CLI takes JSON, and does the deserialization itself. So when showing errors back to users of the CLI, it should show JSON, not Python objects.

Obviously the above are just some quick scribbles, which is a bit unfortunate, but maybe you see one or two small ways to make that nicer looking? Definitely happy to give some more pointers, the offer is as I say definitely appreciated!

**Comment by sloanlance** [comment]
This sounds like a good first issue for me to get an idea of what this project is like internally.  I've already forked the repo, so a good next step for me is to try building in my environment from the master branch.

Do you have an issue for cleaning up `pretty`?  You could assign it to me, if you'd like.  We can use comments there to communicate about it or you can contact me directly.

**Comment by Julian** [comment]
Awesome! There isn't an existing one -- if it's useful obviously feel free to just copy paste the above into a new one definitely sounds like a good way to communicate.

**Comment by sloanlance** [comment]
I've opened #708 for this purpose.

**Comment by Julian** [comment]
Gonna close this one since we're discussing on #708 and the issue originally here hopefully will go out on next release.
