### ISSUE TITLE
Possibility of removing pyrsistent dependency?

### ISSUE THREAD

**Issue by ivandjuricic** [Julian/jsonschema#726]
Hi, we've been using your library a lot in our apps, nice work!

Trouble we encounter is when we want to include schema validation in our serverless microservices with AWS lambdas. We must do manual packaging of pyresistent library as it is not installable via requirements.txt so we have to bundle the package ourselfs manually.

Although this could be ridiculous question but I was wondering on how big of a dependency this is, and how much work will it be to lose this dependency?

**Comment by Julian** [comment]
Hi there.

> Hi, we've been using your library a lot in our apps, nice work!

Much appreciated! Glad it's useful.

I can understand the request here, but unfortunately no, if anything `jsonschema` will likely grow more dependencies over its lifecycle.

I'm not sure what specifically makes `pyrsistent` difficult to package -- I will note since you mentioned it, that Lambda is unfortunately [not specfically supported by this library](https://github.com/Julian/jsonschema/issues/584) though perhaps some of the information there from other users will help you solve the issue you're having with it.

Again appreciate the kind words, and hope you find a solution.
