### ISSUE TITLE
Schema Error with Regex Pattern

### ISSUE THREAD

**Issue by upsteer** [Julian/jsonschema#739]
I have the following schema, which I think is valid to match a list of BSON object Ids:
```python
schema = {'type': 'array', 'items': {'type': 'string', 'pattern': '/^[a-f\d]{24}$/i'}}
example = ['1f62cjahr3cdf3de81812gh7']
jsonschema.validate(instance=example, schema=schema)
```

This results in an error: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/upsteer/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: '1f62cjahr3cdf3de81812gh7' does not match '/^[a-f\\d]{24}$/i'

Failed validating 'pattern' in schema['items']:
    {'pattern': '/^[a-f\\d]{24}$/i', 'type': 'string'}

On instance[0]:
    '1f62cjahr3cdf3de81812gh7'
```

I see that my single backslash is escaped by another backslash. I.e. `\d` is converted to `\\d` which fails the validation.

I just wanted a reason behind this. I also noticed that in Python3:
```python
import json
json.loads(json.dumps({"abc": "\d"}))
```
prints the following: `{'abc': '\\d'}`

Is this what is happening? Or was carried from the json module? 
If so, how do you suggest to solve the problem?

Any suggestions are appreciated. :)

**Comment by Julian** [comment]
Don't think I can look in super detail, but I doubt you're in the right area with the `\\d` -- that's the Python `repr` of `\d` as a regex (or, Python `repr` of a string containing a literal backslash inside of it).

Your issue more likely has to do with your pattern itself -- `/^[a-f\d]{24}$/i` isn't Python regex syntax -- you can try that out with e.g. `re.search(r"/^[a-f\d]{24}$/i", "1f62cjahr3cdf3de81812gh7")`, which won't match the object you're trying to match.

Closing for tidyness (and since I'm not sure there's a bug here, if it's more of a question probably better asked on the Slack). But happy to follow up if indeed you see behavior that looks incorrect.
