### ISSUE TITLE
Issue in a FAQ answer (default property)

### ISSUE THREAD

**Issue by iuridiniz** [Julian/jsonschema#742]
Hello guys, 

In your FAQ, you provide a sample that shows how to make default property set a default value.

If the schema has a 'required' property and it comes before the 'properties' property, a `jsonschema.exceptions.ValidationError` will be raised. 

I think that documentation must be updated in order to avoid this kind of error by someone else. I don't think that this kind of error must be fixed in this project, I think this is outside the scope of the project.

Here a sample:
```python
from jsonschema import Draft7Validator, validators


def extend_with_default(validator_class):
    validate_properties = validator_class.VALIDATORS["properties"]

    def set_defaults(validator, properties, instance, schema):
        for property, subschema in properties.items():
            if "default" in subschema:
                instance.setdefault(property, subschema["default"])

        for error in validate_properties(
            validator, properties, instance, schema,
        ):
            yield error

    return validators.extend(
        validator_class, {"properties" : set_defaults},
    )


DefaultValidatingDraft7Validator = extend_with_default(Draft7Validator)


# Example usage:
obj = {}
schema = {'properties': {'foo': {'default': 'bar'}}}
# Note jsonschem.validate(obj, schema, cls=DefaultValidatingDraft7Validator)
# will not work because the metaschema contains `default` directives.
DefaultValidatingDraft7Validator(schema).validate(obj)
assert obj == {'foo': 'bar'}

# no raises here
obj = {}
schema_required_after_properties = {'properties': {'foo': {'default': 'bar'}, 'required': 'foo'}}
DefaultValidatingDraft7Validator(schema_required_after_properties).validate(obj)
assert obj == {'foo': 'bar'}

# this code will raise jsonschema.exceptions.ValidationError
obj = {}
schema_required_before_properties = {'required': 'foo', 'properties': {'foo': {'default': 'bar'}}}
DefaultValidatingDraft7Validator(schema_required_before_properties).validate(obj)
assert obj == {'foo': 'bar'}
```

**Comment by Julian** [comment]
Hi! Thanks for the report.

I'm probably happy to consider a PR to fix this, though to be honest I'm not sure what the expected fix is -- this way of making `default` work isn't really JSON Schema (i.e. it's not part of the specification), so it's more about what someone doing it expects. `jsonschema` does give tools to allow for implementing whatever behavior is desired here, but I could imagine someone *expecting* the error you're flagging here -- that `required` means "you have to have provided it, otherwise you get a validation error". I could imagine someone *not* expecting that too, so both seem valid, and yeah this isn't part of the spec, so I don't know which behavior someone coming to that page is looking for (in fact personally, I've maintained I'm skeptical of this whole realm -- I think `jsonschema` is good at validation. If someone wants validation + coersion/instantiation/blueprinting whatever you want to call this as either a pre-step or post-step).

But yeah if there's a trivial improvement to be made to the example code, definitely happy to consider it!

#653  is also relevant.

**Comment by timgkeller** [comment]
Hello Julian,

I found another issue with the given example which can be observed when using it in combination with the `anyOf` keyword. I have provided a detailed example and error description on [stackoverflow](https://stackoverflow.com/questions/64552956/setting-defaults-when-validating-a-jsonschema-with-anyof-keyword).

Best regards,
Tim

**Comment by Julian** [comment]
Going to close this given the above, but happy to hear follow-ups.

@timgkeller if you've found another issue you believe to be a bug, happy to see another issue about it, or better a PR.
