### ISSUE TITLE
u prefix in error messages in Python 2 when schema is loaded from file

### ISSUE THREAD

**Issue by abitrolly** [Julian/jsonschema#751]
Given.
```
$  cat schema.json
{
    "type" : "object",
    "properties" : {
        "price" : {"type" : "number"},
        "name" : {"type" : "string"}
    }
}

$ cat sample.json
{"name" : "Eggs", "price" : "xxx"}
```
When running with Python 2, the error message prefixes each field with `u`.
```
$ jsonschema -i sample.json schema.json 
xxx: u'xxx' is not of type u'number'
```
For Python 3 there is no `u` prefix.
```
xxx: 'xxx' is not of type 'number'
```

That's was the reason of tests failure in Poetry - https://github.com/python-poetry/poetry-core/pull/99/checks?check_run_id=1236052810

**Comment by Julian** [comment]
Hi. This is expected behavior, at least until #712, though even afterwards, the exact content of the CLI's output is not part of jsonschema's public API, so this may break at any time if you're doing some sort of exact matching. #673 would likely fix that if you want specifically to test through the CLI, though I haven't looked carefully at what that PR is doing, so not sure I can make a concrete recommendation.

But yeah if you're just asking about the output being valid JSON instead of a Python repr, #712 should fix that.

**Comment by abitrolly** [comment]
The problem is here.

https://github.com/Julian/jsonschema/blob/e48d56cbd2b6c25d4a9483f53f79ec537b9a4a34/jsonschema/_utils.py#L131

It could at least use `%s` specifier for string parameters. The problems repeats for any json loaded from file, which is passed to API.
