### ISSUE TITLE
Default type checker for 'object' seems too narrow

### ISSUE THREAD

**Issue by benmaddison** [Julian/jsonschema#755]
Is there a specific reason that `jsonschema._types.is_object` tests for instances of `dict` rather than the more generic alternative of `collections.abc.Mapping`?

Apologies if this has been asked and answered previously - I couldn't find it in the list of closed issues.

**Comment by Julian** [comment]
Hi there. [Essentially as a balance, because `isinstance` on `collections.abc.Mapping` is quite slow for the majority case.](https://python-jsonschema.readthedocs.io/en/stable/validate/#validating-with-additional-types)

Obviously if you have a more generic thing you can certainly reconfigure your type checker.

Closing but lemme know if anything could use clarifying in the docs.
