### ISSUE TITLE
Support for v2020-12 and v2019 drafts

### ISSUE THREAD

**Issue by gk12277** [Julian/jsonschema#782]
Would be great to have support for the v2020-12 draft. 😄

**Comment by cidrblock** [comment]
+1 

>

**Comment by coxoperationsengineer** [comment]
+1 really looking forward to the unevaluatedProperties features in 2020-12

**Comment by Julian** [comment]
Partial support for these drafts has just landed in v4.0.0.

Feedback more than welcome.

I say partial since unfortunately support for `dynamicRef` did not make it in -- adding support for it is non-trivial. I'm definitely keen on adding it (as soon as possible), but I'm fairly certain doing so reasonably will require revamping `RefResolver`.

Going to close this out for now, but please do share feedback if you have any!
