### ISSUE TITLE
Bug: ModuleNotFoundError: No module named 'jsonschema.compat'

### ISSUE THREAD

**Issue by peterdudfield** [Julian/jsonschema#843]
I'm currently getting the error - ModuleNotFoundError: No module named 'jsonschema.compat'
I think this first started today

I get this on python 3.9.7, when running `import neptune`

This could be an error with 'swagger_spec_validator'

See error [here](https://github.com/openclimatefix/predict_pv_yield/runs/3753388002?check_suite_focus=true)

For reference I have also created a big report here: https://github.com/Yelp/swagger_spec_validator/issues/149

**Comment by meanderingsquirreleatsnuts** [comment]
Getting the same error too, it started 9hrs ago   

 import python_jsonschema_objects as jso
/home/builder/.local/lib/python3.6/site-packages/python_jsonschema_objects/__init__.py:12: in <module>
    from jsonschema.compat import iteritems
E   ModuleNotFoundError: No module named 'jsonschema.compat'

**Comment by peterdudfield** [comment]
<img width="1224" alt="Screenshot 2021-09-30 at 09 39 12" src="https://user-images.githubusercontent.com/34686298/135418233-7ec19cc9-e9a5-424f-91f6-39e21faf4424.png">

Seems to be a move away from iteritems, to '.items()' instead

**Comment by svart-riddare** [comment]
I do not know if this is related or not to https://github.com/p1c2u/openapi-spec-validator/issues/130, another openapi validator that stopped working when upgrading to jsonschema 4.0.0.

**Comment by peterdudfield** [comment]
I've created a PR that added compact.py back in with a warning

**Comment by peterdudfield** [comment]
> I do not know if this is related or not to [p1c2u/openapi-spec-validator#130](https://github.com/p1c2u/openapi-spec-validator/issues/130), another openapi validator that stopped working when upgrading to jsonschema 4.0.0.

This looks a different issue, but also related to the release of 4.0.0

**Comment by Julian** [comment]
Hi all.

`jsonschema.compat` was documented both [in its docstring](https://github.com/Julian/jsonschema/blob/3ececbd66dc8190287e7c9cd7c87387c637f1d19/jsonschema/compat.py#L4) as well as in a note in the [documentation](https://python-jsonschema.readthedocs.io/en/v3.2.0/faq/#how-do-jsonschema-version-numbers-work) as being private. It was also never documented to end-users (i.e. other than that note, no list of what's in there appeared anywhere). The reason it existed at all was simply because `jsonschema` is going on 9 years now and existed before something like [six](https://pypi.org/project/six/) was usable, otherwise it would have used it -- it definitely was not intended (or promised to be usable) by any other users than `jsonschema` itself.

So it's unfortunate some downstream packages used things from it anyhow, but it's not covered by the deprecation policy. These packages should remove their use of it and use `six` or an equivalent if they're still supporting versions where it's needed.
