### ISSUE TITLE
Load schemas via importlib.resources instead of pkgutil

### ISSUE THREAD

**Issue by sevein** [Julian/jsonschema#871]
Producing binaries that embed Python applications that import jsonschema is challenging because `pkgutil.get_data` relies on `__file__` which may not be always defined, e.g. see [these issues](https://github.com/indygreg/PyOxidizer/issues?q=is%3Aissue+is%3Aopen+jsonschema) in PyOxidizer.

https://github.com/Julian/jsonschema/blob/272b4f24437d9cba1127058dc3479f9bc6d8c4b9/jsonschema/_utils.py#L49-L55

I was wondering if this project would be interested in having a fallback implemented that is capable to load the schema files using `importlib.resources` instead, which was added in Python 3.7. See https://stackoverflow.com/a/20885799 for more details. The creator of PyOxidizer, Gregory Szorc, shares some good details on loading resource files using PyOxidizer [here](https://pyoxidizer.readthedocs.io/en/latest/oxidized_importer_resource_files.html#resource-files).

**Comment by Julian** [comment]
Hi. `importlib.resources` is going through some instability now (having lots of APIs deprecated), which is something I haven't paid a ton of attention to.

In theory now that we're 3.7+ I'm indeed open to the idea of using it if we can do so without raising deprecation warnings on other versions, so a PR would be welcome --

I'll also just point out though that support for pyoxidizer (or pyinstaller, or cx_freeze, or etc.) is unofficial because jsonschema isn't run under it in CI, so whilst I'm OK with this proposal for independent reasons (that importlib.resources is the new way to do this), I can't really promise in the future that things will continue to work.

**Comment by Julian** [comment]
Cool!

I'd rather not use a function that's already been deprecated, unless it shakes out that it's going to be undeprecated which last I saw seemed unclear that that'd happen.

So I'd prefer the second route with the backport for pre-3.9, which I hear has its own perils but seems at least like the supported route by the upstream folks.
